// Generated by tools/build_sw.py — do not edit by hand. Version a93d5b362f, 70 files.
const VERSION = 'casino-a93d5b362f';
const FILES = ["assets/img/cards/AC.jpg", "assets/img/cards/AD.jpg", "assets/img/cards/AH.jpg", "assets/img/cards/AS.jpg", "assets/img/cards/JC.jpg", "assets/img/cards/JD.jpg", "assets/img/cards/JH.jpg", "assets/img/cards/JS.jpg", "assets/img/cards/KC.jpg", "assets/img/cards/KD.jpg", "assets/img/cards/KH.jpg", "assets/img/cards/KS.jpg", "assets/img/cards/QC.jpg", "assets/img/cards/QD.jpg", "assets/img/cards/QH.jpg", "assets/img/cards/QS.jpg", "assets/img/cards/back.jpg", "assets/img/cards/credit-1.jpg", "assets/img/cards/credit-2.jpg", "assets/img/cards/credit-3.jpg", "assets/img/cards/credit-4.jpg", "assets/img/cards/credit-5.jpg", "assets/img/chips/1.png", "assets/img/chips/100.png", "assets/img/chips/1000.png", "assets/img/chips/25.png", "assets/img/chips/5.png", "assets/img/chips/500.png", "assets/img/chips/5000.png", "assets/img/icon-180.png", "assets/img/icon-512.png", "assets/img/lobby/floor.jpg", "assets/img/portraits/freddy.png", "assets/img/portraits/ken-mad.jpg", "assets/img/portraits/ken.jpg", "assets/img/portraits/kurtis.png", "assets/img/portraits/mom.png", "assets/img/portraits/nathaniel.png", "assets/img/portraits/nic.png", "assets/music/song-1.mp3", "assets/music/song-2.mp3", "assets/sfx/check.mp3", "assets/sfx/deal.mp3", "assets/sfx/lose.mp3", "css/app.css", "index.html", "js/app.js", "js/content/characters.js", "js/content/lines.js", "js/content/lobby.js", "js/content/tables.js", "js/content/tiers.js", "js/core/ai.js", "js/core/assets.js", "js/core/audio.js", "js/core/bank.js", "js/core/blackjack.js", "js/core/cards.js", "js/core/evaluator.js", "js/core/poker.js", "js/core/rng.js", "js/ui/blackjackSelect.js", "js/ui/blackjackTable.js", "js/ui/components.js", "js/ui/dom.js", "js/ui/holdemSelect.js", "js/ui/holdemTable.js", "js/ui/lobby.js", "js/ui/tableSelect.js", "manifest.webmanifest"];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(FILES.map((f) => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
// Cached files come straight from the cache (fast, works offline). Anything else goes to the network,
// and a successful same-origin answer is kept so optional art you add later works offline too.
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== self.location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(e.request, copy)); }
    return res;
  })));
});
