#!/usr/bin/env python3
"""Regenerate sw.js — the offline cache list. Run after adding or changing any file:  python3 tools/build_sw.py
The version is a hash of every listed file, so the phone picks up changes on its next launch."""
import hashlib, os, json
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
KEEP = ('.html', '.css', '.js', '.webmanifest', '.png', '.jpg', '.jpeg', '.webp', '.mp3', '.m4a', '.wav', '.ogg')
files = ['index.html', 'manifest.webmanifest']
for top in ('css', 'js', 'assets'):
    for d, _, fs in os.walk(top):
        for f in fs:
            if f.lower().endswith(KEEP):
                files.append(os.path.join(d, f).replace(os.sep, '/'))
files = sorted(set(files))
h = hashlib.sha1()
for f in files:
    h.update(f.encode()); h.update(open(f, 'rb').read())
version = h.hexdigest()[:10]
sw = f"""// Generated by tools/build_sw.py — do not edit by hand. Version {version}, {len(files)} files.
const VERSION = 'casino-{version}';
const FILES = {json.dumps(files)};
self.addEventListener('install', (e) => {{
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(FILES.map((f) => new Request(f, {{ cache: 'reload' }})))).then(() => self.skipWaiting()));
}});
self.addEventListener('activate', (e) => {{
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
}});
// Cached files come straight from the cache (fast, works offline). Anything else goes to the network,
// and a successful same-origin answer is kept so optional art you add later works offline too.
self.addEventListener('fetch', (e) => {{
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== self.location.origin) return;
  e.respondWith(caches.match(e.request, {{ ignoreSearch: true }}).then((hit) => hit || fetch(e.request).then((res) => {{
    if (res.ok) {{ const copy = res.clone(); caches.open(VERSION).then((c) => c.put(e.request, copy)); }}
    return res;
  }})));
}});
"""
open('sw.js', 'w').write(sw)
total = sum(os.path.getsize(f) for f in files)
print(f'sw.js written: version {version}, {len(files)} files, {total/1e6:.1f} MB cached offline')
